### ISSUE TITLE
Pop up an error when creating a new blob named "this/is/a/new/blob.txt"

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurestorage#606] opened 2020-02-10 08:15 UTC
**OS**: All
**Build Version:** [20200209.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14542&view=results)

**Repro Steps:**
1. Create a new storage account --> Create a new blob container.
2. **Create multiple blobs.**
3. Make sure there are some existing blobs --> Create a new blob named "this/is/a/new/blob.txt".
4. Check the result.

**Expect:**
Succeed to create this new blob.

**Actual:**
Pop up an error when creating the new blob with this name.
![image](https://user-images.githubusercontent.com/34729092/74131577-996d5d80-4c1f-11ea-8337-4b90235dfd1d.png)

**More Info:**
This issue doesn't reproduce when creating the first blob with name "this/is/a/new/blob.txt" directly.

**Comment by wwlorey** [comment] 2020-02-10 17:22
Closing as dupe of https://github.com/microsoft/vscode-azurestorage/issues/601

**Closed by wwlorey** 2020-02-10 17:22 UTC
Labels: AT-CTI, duplicate
