### ISSUE TITLE
Directly overwrite the existed file when uploading the same file again

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#676] opened 2020-05-20 10:15 UTC
**OS:** Windows
**Build Version:** [20200519.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19680&view=artifacts&type=publishedArtifacts)

**Repro Steps:**

1. F1--> Azure Storage: Upload to Azure Storage--> Uploading a file--> Select subscription--> Select Storage Account-->Select resource type--> Select Blob container 
2. Verified successfully upload to blob container 
3. Upload the same file to this blob container again
4. Check the result

**Expect:**
Pop up a prompt to ask to overwrite or not, such as:
![image](https://user-images.githubusercontent.com/62053665/82425763-8f2deb80-9ab9-11ea-95d9-fbd03b45afec.png)

**Actual:**
Directly overwrite the existed file without any prompt.

**More info:**
This issue does not reproduce when use "Upload Block Blob...".

**Comment by wwlorey** [comment] 2020-05-20 21:40
Closing as by design

**Closed by wwlorey** 2020-05-20 21:40 UTC
Labels: AT-CTI, by design
