### ISSUE TITLE
Succeed to delete one blob container which contains a blob that has a snapshot

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#675] opened 2020-05-20 10:15 UTC
**OS:** Windows
**Build Version:** [20200519.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19680&view=artifacts&type=publishedArtifacts)

**Repro Steps:**

1. Delete a blob that has a snapshot 
2. Fail to delete the blob and pops up an error message:
 ![image](https://user-images.githubusercontent.com/62053665/82433648-55161700-9ac4-11ea-8cf0-480e29752b25.png)
3. Delete this blob container that has a snapshot
4. Check the result

**Expect:**
Fail to delete the blob container.

**Actual:**
Succeed to delete the blob container.

**Comment by wwlorey** [comment] 2020-05-20 21:52
Closing as by design. Since we make an SDK call to delete, that functionality isn't something we can change. Feel free to confirm with @v-xianya if needed

**Closed by wwlorey** 2020-05-20 21:52 UTC
Labels: AT-CTI, by design
