### ISSUE TITLE
Can't upload a file/folder to a file share by executing "Azure Storage: Upload Files..." command from command palette

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurestorage#1198] opened 2023-02-02 09:28 UTC
**OS:** All
**Build Version:** 20230201.1
**Regression:** Preview Release

**Repro Steps:**

1. F1 -> Azure Storage: Upload Files... -> Select a file -> Select a resource.
2. Check whether the next step is "Select resource type" or not.

**Expect:**
The next step is "Select resource type".
![image](https://user-images.githubusercontent.com/107091828/216282770-8bbbe7bf-0680-4c19-9eec-0e0adaffeb2b.png)

**Actual:**
The next step is "Select Blob Container".

**More Info:**
1. This issue also reproduces when executing "Azure Storage: Upload Folder..." command.
2. This issue also reproduces when executing "Azure Storage: Open in Explorer..." command.

**Comment by alexweininger** [comment] 2023-02-03 18:21
Caused by https://github.com/microsoft/vscode-azurestorage/pull/1196/files#diff-55d05f2d9760fbd2a6522bb5d050f48cb375bf5791db826a9455ab4c0eff8634.

We either need to implement a one-off quick pick inside `pickTreeItemImpl`, or add `isAncestorOf` support to the compat shim. I'm going to try to add `isAncestorOf` to the shim since that should result in fixing bugs for other extensions too.

**Comment by alexweininger** [comment] 2023-02-03 23:37
@v-chenzha this should be fixed now, can verify the fix?

**Closed** 2023-02-03 23:36 UTC
Labels: 🐛 bug, AT-CTI, v1.5 shim

**Comment by v-chenzha** [comment] 2023-02-06 01:46
@alexweininger  Verified this issue on the latest build 20230205.1, it does not reproduce.
