### ISSUE TITLE
Show a warning "<workspacename> unable to resolve workspace folder" in the new opened File Explorer when the resource groups by Resource Type/Location/ARM Tag

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#1042] opened 2022-05-06 09:23 UTC
**OS:** All
**Azure Resource Extension Build Version:** 20220505.12 (unified)
**Azure Storage Extension Build Version:** 20220505.2 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the resource groups by **Resource Type/Location/ARM Tag**.
2. Expand a storage account -> Expand a Blob Containers -> Right click a blob container -> Click "Open in File Explorer..." -> Click "Open in new window".
3. Check whether shows all folders and blobs that are under the blob container in the new opened File Explorer.

**Expect:**
Show all folders and blobs that are under the blob container in the new opened File Explorer.

**Actual:**
Show a warning "<workspacename> unable to resolve workspace folder" in the new opened File Explorer.
![image](https://user-images.githubusercontent.com/57662131/167100830-cdbd595e-8ae5-4b8f-a58e-86f1134b0038.png)

**More Info:**

1. This issue also reproduces when opening a file share in File Explorer.
2. This issue also reproduces when selecting "Open in current window" or "Add to workspace".
3. This issue doesn't reproduce when the resource groups by Resource Group.

**Comment by nturinski** [comment] 2022-05-06 19:53
Should be fixed by fixing this https://github.com/microsoft/vscode-azurestorage/issues/1041

**Comment by v-ruizh** [comment] 2022-05-18 09:01
This issue can be reproduced on the latest main branch build 20220518.1. And it also reproduces when the resource groups by "Resource Group".

**Comment by nturinski** [comment] 2022-05-19 06:06
This bug is somewhat nasty.  I know for sure that it wasn't working because we weren't finding the tree item correctly unless it was in resourceGroup grouping.  After my fix, I think it broke again because we aren't resolving all of the children automatically anymore.  

To fix this bug, you have to open the appropriate group, let it resolve, and then refresh the tree item (so that its children appear).  Once you've done that, refresh the workspace, and everything works as expected.


It has decent usage and I would want to fix it, but I'm not really sure how we would.

**Comment by nturinski** [comment] 2022-05-19 07:12
What happens is, findTreeItem is called.  It automatically calls `getCachedChildren,` but since the StorageTreeItem Proxy isn't resolved yet, it returns an empty array.  We probably need to make findTreeItem also resolve the AppResource (unless we are looking for that node and are done)

**Comment by bwateratmsft** [comment] 2022-05-19 12:42
@nturinski I think you're right; `findTreeItem` is selecting for a single node so resolving it shouldn't be a big deal.

**Closed** 2022-05-20 01:35 UTC
Labels: 🐛 bug, AT-CTI, unified

**Comment by v-ruizh** [comment] 2022-05-20 03:13
Verified this issue on the build 20220520.3, it does not reproduce.
