### ISSUE TITLE
 Pop up an error after deleting a folder for a blob container

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurestorage#1093] opened 2022-07-15 08:52 UTC
**OS:** Win 10
**Build:** 20220714.11
**Regression:** Not a regression

**Repro Steps:**

1. Expand a storage account -> Create a blob container 
2. Right click the blob container -> Click "Create Empty Blob..." -> Type name "a/b.txt".
3. Right click the blob container again -> Click "Create Empty Blob..." -> Type name "a/c/d.txt".
4. Right click "a" folder ->Click "Delete..." 
5. Check whether no error pops up.

**Expect:**
No error pops up.

**Actual:**
Pop up an error 'Failed with code "404"'.
![image](https://user-images.githubusercontent.com/107091828/179184313-908d130d-6145-4b90-8c3b-5c384f7189c2.png)

**Comment by alexweininger** [comment] 2022-08-09 23:02
This might be related to or a duplicate of #1073

**Closed** 2022-08-09 23:31 UTC
Labels: 🐛 bug, AT-CTI, P1
