### ISSUE TITLE
Can't get the functional website after deploying successfully

### ISSUE THREAD

**Issue by v-haiz** [microsoft/vscode-azurestorage#231] opened 2018-09-27 09:41 UTC
**Version**: 0.4.1
**Platform/OS Version**: Windows 10/ Linux Ubuntu 16.04/ MacOS High Sierra

**Repro Steps**:
1. Create a StorageV2 account -> Enable the Static website and set 'Index document name' to 'index.html' in portal .
2.  Deploy the StorageV2 account to Static Website successfully -> Browse Static Website.
3. Check the result.

**Expect**:
Succeed to see the functional website.

**Actual**:
Get the 'The requested content does not exist' page.
![actual](https://user-images.githubusercontent.com/37653604/46134968-a7d9f580-c233-11e8-9862-52be607c50dc.png)

**Comment by StephenWeatherford** [comment] 2018-10-12 20:33
@v-haiz Are you still seeing this?

**Comment by StephenWeatherford** [comment] 2018-12-05 21:53
What source code are you publishing?

**Comment by v-xianya** [comment] 2018-12-14 09:38
Verified with build 20181213.1. This issue also reproduces.
**More Info:** 
I published the 'dist', please get it from [https://github.com/gothinkster/vue-realworld-example-app](url)

**Comment by davidsblom** [comment] 2019-02-17 14:17
I have the same problem. Any clues what could be the cause?

**Comment by StephenWeatherford** [comment] 2019-02-19 19:08
Whenever I've seen this it's been because the index document name was not set to a valid blob name (right-click on account -> Configure Static Website... -> make sure the path you enter exists as a blob name).

**Comment by StephenWeatherford** [comment] 2019-02-19 19:21
@v-xianya Can you point me to the website that you created?  Thx.

**Comment by v-xianya** [comment] 2019-02-20 05:54
Hi @StephenWeatherford 
Verified with the latest build [20190219.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3322&view=results). This issue doesn't reproduce.

**Comment by MDBrittingham** [comment] 2020-01-07 20:14
Remember!  Azure blob storage is case sensitive.  If you tell it that the default document is "default.html" but your document is "Default.html" then you will get the error you mentioned.

**Comment by nturinski** [comment] 2020-01-29 23:09
Closing as it doesn't repro with build https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3322&view=results

**Closed by nturinski** 2020-01-29 23:09 UTC
Labels: AT-CTI

**Comment by ankitamallick3** [comment] 2020-02-12 16:41
@MDBrittingham  Thank you so much for this ! My html page is finally opening without errors
