### ISSUE TITLE
Unable to create azurestorage on student subscription

### ISSUE THREAD

**Issue by kavoo** [microsoft/vscode-azurestorage#862] opened 2020-10-22 06:09 UTC
Does this occur consistently? 
Repro steps:

1. right-click on azure subscription, create a storage account (tried regular and advanced option)
2. it fails to create
I had some resources in this account earlier, which I deleted and now trying to create a static website

Action: azureStorage.createGpv2AccountAdvanced
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Storage'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 0.10.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:31:74264
extension.bundle.js:31:763360extension.bundle.js:31:763360
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by kavoo** [comment] 2020-10-22 06:15
I had a resourcegroup with the same name, so it is technically not an issue but misleading error information.

**Comment by kavoo** [comment] 2020-10-22 06:16
after deleting the same name resource group, I tried creating the resource again, and found it still fails with the same error, hence reopening.

**Comment by wwlorey** [comment] 2020-10-22 18:50
@kavoo thanks for filing. This is a duplicate of https://github.com/microsoft/vscode-azurestorage/issues/845 and was fixed in https://github.com/microsoft/vscode-azurestorage/pull/858 which will ship in our next release.

**Closed by wwlorey** 2020-10-22 18:50 UTC
