### ISSUE TITLE
Saving a blob which has been deleted succeeds

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-azurestorage#106] opened 2018-03-28 10:16 UTC
Repro Steps:
1. Right click one 'Blob Container' and select 'Create Blob Container'.
2. Right click the blob container and select 'Create Empty Text Blob' named 'testblob'.
3. Open the text blob, then delete the 'testblob'.
4. Edit the test blob in the opened blob editor, then update it.

Expect:
Fail to update the text blob.

Actual:
Success to update the text blob.

More Info:
This issue doesn't reproduce for file share. 
![fileshare](https://user-images.githubusercontent.com/34729092/38023152-073f1f94-3271-11e8-89c8-8640bc868181.png)

**Comment by v-flyuan** [comment] 2018-04-03 09:27
More Info:
After updating the file 'testblob' successfully, the 'testblob' will be added back under blob container.

**Comment by StephenWeatherford** [comment] 2018-04-03 19:20
Personally I'm inclined to think this is a desirable feature rather than a bug. The only minor issue being that it won't show up in the tree without a refresh.

**Comment by StephenWeatherford** [comment] 2018-04-18 22:34
By design.  Or won't fix.  :-)

**Closed by StephenWeatherford** 2018-04-18 22:34 UTC
