### ISSUE TITLE
The destination folder doesn't automatically appear in Azure view after executing "Upload Files..." command

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#855] opened 2020-10-20 09:47 UTC
**OS:** Mac
**Build Version:** 20201019.1

**Repro Steps:**

1. Expand a attached storage account -> Right click the "Blob Containers" node -> Create a new blob container.
2. Right click the blob container -> Select "Upload Files..." --> Select a file --> Enter a destination directory with "test".
3. Check the result.

**Expect:**
The destination folder automatically appears in Azure view.

**Actual:**
The destination folder doesn't automatically appear in Azure view.

**More Info:**
1. This issue doesn't reproduce after entering a destination directory during executing "Upload Folder...".
2. This issue does not reproduce after refreshing.

**Comment by nturinski** [comment] 2020-10-21 21:54
Closing as dupe of https://github.com/microsoft/vscode-azurestorage/issues/826

**Closed by nturinski** 2020-10-21 21:54 UTC
Labels: AT-CTI
