### ISSUE TITLE
[Linux]Fail to paste the copied connection string to editor

### ISSUE THREAD

**Issue by v-haiz** [Microsoft/vscode-azurestorage#205] opened 2018-07-30 10:50 UTC
**Repro Steps**:
 1. Choose a storage account -> Right click it and select 'Copy Connection String'.
 2. Paste the copied connection string to editor.
 3. Check whether the connection string can be pasted to editor successfully or not.

**Expect**:
 Succeed to paste the copied connection string to editor.

**Actual**:
 Fail to paste connection string to editor .

**More Info**:
 1. Also fail to paste blob container/file share url to editor.
 2. This issue doesn't reproduce on Windows/Mac.

**Comment by StephenWeatherford** [comment] 2018-07-30 21:01
Repros in 0.4.0

**Comment by EricJizbaMSFT** [comment] 2018-07-30 21:07
Closing as dupe of https://github.com/Microsoft/vscode-azurestorage/issues/141

**Closed by EricJizbaMSFT** 2018-07-30 21:07 UTC
Labels: CTI
