### ISSUE TITLE
An error occurs after opening a blob container in the explorer

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurestorage#1219] opened 2023-02-17 07:44 UTC
**OS:** Win10
**Azure Resource Group Build Version:** 20230215.10
**Azure Storage Build Version:** v0.15.1

**Repro Steps:**

1. Create a storage account -> Create a new blob container -> Right click the blob container -> Click "Open in Explorer..." -> Click "Open in current window".
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/107091828/219572661-f335d5de-acdf-424f-ba8f-b4575744e0ac.png)

**More info:**
1. This issue also reproduces when opening in a new window and adding to workspace.
2. This issue also reproduces for the file share.

**Comment by alexweininger** [comment] 2023-02-17 20:52
That's a new one! I cannot reproduce it, but it seems like a service issue, hopefully unrelated to any v2 changes.

**Comment by v-chenzha** [comment] 2023-02-20 06:02
@alexweininger  Verified on the latest main branch Resource Groups extension build 20230219.1, this issue still reproduces for now.
It takes about 3 minutes to load after selecting open in explorer, and then the error will pop up.

**Comment by alexweininger** [comment] 2023-02-22 23:20
Marking as wont fix.

**Closed by alexweininger** 2023-02-22 23:20 UTC
Labels: 🐛 bug, AT-CTI
