### ISSUE TITLE
[Suggestion] Add the logs for saving the blob changes in File Explorer

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurestorage#450] opened 2019-08-20 09:42 UTC
**OS:** All
**Build Version:** [20190818.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8954)
**Regression:** Not a Regression

**Repro Steps:**

1. Enable "Azure Storage: Enable View in File Explorer" in User Setting.
2. Drill down from one storage account --> "Blob Containers" node -->Expand one blob container --> Click "Open in File Explorer...".
3. Create a new file--> Edit this file--> 'Ctrl+S' to save this change.
4. Check the logs for this process.

**Suggestion:**
Add the logs for this process in notification or output panel.

**Actual:**
"Save blob..." progress bar flashes and there is no log in notification or output panel after this process finished.

**More info:**
This issue also reproduces for File Shares.

**Comment by PrashanthCorp** [comment] 2019-09-04 22:55
It works as intended. Closing this.

**Closed by PrashanthCorp** 2019-09-04 22:55 UTC
Labels: AT-CTI, enhancement
