### ISSUE TITLE
[Suggestion] Add a notification when successfully created a storage account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#672] opened 2020-05-19 09:07 UTC
**OS:** Windows
**Build Version:** [20200518.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19591&view=artifacts&type=publishedArtifacts)

**Repro Steps:**

1. Right click the applied subscription -->Select 'Create Storage Account…(Advanced)'
2. Enter a name--> Select a resource group--> Select "No"--> Select a location
3. Check the result

**Actual:**
There is receive a notification during creating a storage account, but don’t receive a notification when the creation is complete.

**Suggestion:**
Add a notification when successfully created a storage account.

**Comment by wwlorey** [comment] 2020-05-20 21:56
Closing as by design since we log a successful create to the output channel

**Closed by wwlorey** 2020-05-20 21:56 UTC
Labels: AT-CTI, by design
