### ISSUE TITLE
The webpage displays incorrectly when deploying with a new created account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestorage#821] opened 2020-09-22 07:01 UTC
**OS:** Win10
**Build Version:** 20200917.13

**Repro Steps:**
1. F1 --> Click  "Deploy to Static Website via Azure Storage…" --> Select the folder --> Select the subscription --> Select "+Create new Storage Account..." --> Enter a name --> Press Enter.
2. Browser the website after finishing deployment.

**Expect:**
The webpage displays correctly.

**Actual:**
The webpage displays incorrectly.
![image](https://user-images.githubusercontent.com/57662131/93840312-8f85ff80-fcc2-11ea-81d4-b87ed39f45e1.png)

**More Info:**
1. This issue also reproduces when executing "Deploy to Static Website via Azure Storage…" command from Explorer.
2. This issue doesn't reproduce when Click the "Deploy to Static Website via Azure Storage…" button.
3. This issue will be fixed after refreshing the webpage.

**Comment by nturinski** [comment] 2020-09-23 21:39
Since this is fixed by a refresh, this seems like a timing issue.  We don't know how long we would have to delay to guarantee it works.  Regarding More Info 1&2, it probably is just a timing issue and could reproduce/not reproduce on both.

Anyway, one possible fix is to ping the site first and make sure it is not reporting 404 before we say that it is finished.

**Closed** 2021-05-23 07:24 UTC
Labels: AT-CTI
