### ISSUE TITLE
[Codespace] No prompt on file close, inconsistent comparing to running VS Code local

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/vscode-azurestorage#895] opened 2020-12-03 01:49 UTC
In the storage extension in VS Code, if you modify a file/blob, the tab is changed from 'X' to a dot, indicating the file is polluted/changed/modified. If you click on the dot to just close the tab, you will be prompted with a dialog asking if you want to "Save", "Don't Save", "Cancel" the changes.  However, if you just use ctrl+S or cmd+S to save the file, it does not prompt with the dialog. However, in VS Code Codespaces, if you after you have modified the file and click to close the tab, we don't prompt for anything, but the file indeed is saved (so no data loss).  The two experiences are inconsistent.  Here is one of the repro scenario:

1. In a storage account, create a new blob container, or use an existing blob container
2. In the container, create an empty blob named "test.txt"
3. Double click on test.txt to open it for editing
4. Type something in the editor.  Notice two things:

Actual result:
1. There is no indication that the file is polluted/changed/modified.  The tab still has an 'X' even after you added something to the blob/file
2. If you click on 'X' to close the file/blob, there is no dialog or prompt or any message indicating whether my changes were saved or lost.  The VS Code experience actually brings up the dialog I mentioned in the beginning paragraph.

The changes were saved however.

**Comment by wwlorey** [comment] 2020-12-04 17:18
Duplicate of https://github.com/microsoft/vscode-azurestorage/issues/875.

@jinglouMSFT This is definitely a design decision they made in Codespaces, perhaps because editing files in a web browser presents the risk of losing data due to poor connection or any number of factors. I asked this in the original issue but do you think it's worth filing an issue on Codespaces for this? I could see potential issues with constantly saving a blob/file. But the possibility of losing data sounds worse

**Comment by wwlorey** [comment] 2020-12-10 22:31
Closing based on https://github.com/microsoft/vscode-azurestorage/issues/875#issuecomment-742841447

**Closed by wwlorey** 2020-12-10 22:31 UTC
Labels: Codespaces, duplicate
