### ISSUE TITLE
error when deploy app to static website azure storage account 

### ISSUE THREAD

**Issue by yaffaharari** [microsoft/vscode-azurestorage#649] opened 2020-03-15 18:57 UTC
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureStorage.deployStaticWebsite
Error type: Error
Error Message: Error uploading "c:/Users/user/Desktop/Yaffa/WebstormProjects/newsServer-GUI/node_modules/@angular/core/esm2015/src/linker/query_list.js": Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:650e92b5-301e-0056-30f4-fa0c5d000000
Time:2020-03-15T18:07:50.3508872Z 

Version: 0.9.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code - Insiders
Product Version: 1.44.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:157:132413
rejected extension.bundle.js:157:131773
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment] 2020-03-16 17:44
Closing as a dupe of https://github.com/microsoft/vscode-azurestorage/issues/219

**Closed by nturinski** 2020-03-16 17:44 UTC
