### ISSUE TITLE
[Suggestion] Add a notification when successfully upload to blob container

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestorage#673] opened 2020-05-20 07:41 UTC
**OS:** Windows
**Build Version:** [20200519.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19680&view=artifacts&type=publishedArtifacts)

**Repro Steps:**

1. F1--> Azure Storage: Upload to Azure Storage--> Uploading a file--> Select subscription--> Select Storage Account-->Select resource type--> Select Blob container 
2. Check the result

**Actual:**
There is a notification during uploading a file, but don’t receive a notification when successfully upload to blob container.

**Suggestion:**
Add a notification when successfully upload to blob container.

**Comment by wwlorey** [comment] 2020-05-20 21:56
Closing as by design since we log a successful upload to the output channel

**Closed by wwlorey** 2020-05-20 21:56 UTC
Labels: AT-CTI, by design
